spring:
  application:
    name: renderConsumer

  rabbitmq:
    uri: ${SPRING_RABBITMQ_URI}
    addresses: amqps://gicdzucg:LkSM27kzjstopmsskbf8WL_N9HkIcovd@kingfisher.lmq.cloudamqp.com/gicdzucg

server:
  port: 9090